scaffolded npc table
teamup-apps-for-good/fin-lit-quest pull request #10
Opened 2024-01-08 02:06 UTC by jamlol

generated table for nonplayers

2024-01-08 15:19 UTC, TengMengTing commented
Should we have CRUD for this table? I'm thinking Users will never create NPCs, and we lilely wont ever create from gui. Thus getting rid of the create, edit, delete functions and only have read. We will be seeding in all of the NPCs .

2024-01-08 15:21 UTC, TengMengTing requested changes
Should we have CRUD for this table? I'm thinking Users will never create NPCs, and we lilely wont ever create from gui, so we should probably be getting rid of the create, edit, delete functions and only have read. We will be seeding in all of the NPCs .

2024-01-09 00:16 UTC, TengMengTing approved these changes
Scrap the previous comment, CRUD will be good for admin purposes

2024-01-09 00:24 UTC, naam1595am approved these changes

2024-01-09 00:24 UTC, merged